### ISSUE TITLE
Missing opening `html` tag in `devise` layout of light theme

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#112]
https://github.com/bullet-train-co/bullet_train-core/blob/f87143fbc2dd41a5e97b76be22971f95fb22cbca/bullet_train-themes-light/app/views/themes/light/layouts/_devise.html.erb#L1-L3

**Comment by jagthedrummer** [comment]
Relatedly, it's missing the theme classes that should be on the opening html tag.

**Comment by jagthedrummer** [comment]
I'm thinking that maybe this was an accidental removal?

https://github.com/bullet-train-co/bullet_train-core/pull/106/files#diff-1fc68ed0b53bacc67d976dbe546254e88c0e4016a29ec3396680ce86505ce4a4L2
