### ISSUE TITLE
`text-2xs` does more than it should

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#116]
https://github.com/bullet-train-co/bullet_train-core/blob/5312a6271f0c896e230bbeac743428d866e949b5/bullet_train-themes-light/app/assets/stylesheets/light/tailwind/utilities.css#L3-L9

I was a bit surprised to find that the `text-2xs` class actually applies `uppercase` as well. This seems to be at odds with the tailwind philosophy of how to compose classes.

I would also expect to find the definition for `2xs` in the `tailwind.config.js` next to the definition of `xs` that is already there.

https://github.com/bullet-train-co/bullet_train-core/blob/f87143fbc2dd41a5e97b76be22971f95fb22cbca/bullet_train-themes-light/tailwind.light.config.js#L19-L21

It is possible to combine multiple attributes into a single class in the tailwind config like this...

https://github.com/tailwindlabs/tailwindcss/blob/316282d719d141b184a71349021ad51d8aee1950/stubs/defaultConfig.stub.js#L331-L344

At the very least, if you want to have a single class for things like labels, then it shouldn't be named the same way one would expect a tailwind class to be named.

**Comment by jagthedrummer** [comment]
Good find on this! I've wondered why some stuff seemed to be inexplicably upper cased. I bet this is it.
