### ISSUE TITLE
Double Printing Username 

### ISSUE THREAD

**Issue by regularlady** [bullet-train-co/bullet_train-core#13]
Hi, Andrew and team! 

I pulled down and upgraded my app using the handy upgrade guide today (12/18/22).

In the Bullet Train Light theme, if you choose to keep the side navigation, the user name and team name print twice on the nav. I commented out the rest of the menu so you can see the double print in the screenshot below. 

![Screen Shot 2022-12-18 at 5 52 59 PM](https://user-images.githubusercontent.com/2446523/208323559-11fdeb46-2f92-4e6b-b936-3aeaec9bc631.png)

I believe this is caused by the conditional being "side" instead of "left". I needed to use "left" after looking at the codebase to go back from the top nav. 

Where I saw :left

https://github.com/bullet-train-co/bullet_train-core/blob/e479798bdb6abfe4840ac71549ce94309eac0882/bullet_train-themes-light/app/views/themes/light/layouts/_account.html.erb#L15

Where I see :side

https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-themes-light/app/views/themes/light/menu/_account.html.erb#L16

My config/initializers/theme.rb

```
# frozen_string_literal: true

BulletTrain::Themes::Light.navigation = :left
BulletTrain::Themes::Light.color = :blue
BulletTrain::Themes::Light.original_devise_path = `bundle show devise`.chomp
```

I'm hoping I'm making a config mistake 🤞 

Thank you for all of your work on Bullet Train, it is really awesome!

**Comment by gazayas** [comment]
Hello @regularlady, thanks for reporting!

Since the navigation code is new I'm not sure if it's related to [this issue](https://github.com/bullet-train-co/bullet_train/issues/550), but I'll link it here just in case. Super Scaffolded views were mainly affected there so I don't think it should have affected the navbar, but if I find anything I'll be sure to post here.

**Comment by andrewculver** [comment]
@regularlady Hey, can you try upgrading again and let me know if you still run into this issue?

**Comment by regularlady** [comment]
@andrewculver I pulled in the new changes since I last attempted to upgrade and it is still happening. Do you recommend I start the upgrade over again?

**Comment by andrewculver** [comment]
@regularlady Going to reach out via Twitter DM.

**Comment by regularlady** [comment]
@andrewculver I'm going to close since I'm not having this issue on a fresh install. Thank you for looking! <3 DMing this to you on Twitter as well.
