### ISSUE TITLE
Use `crud-field` for core models

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#132]
Context: https://discord.com/channels/836637622432170028/1078253154606522481/1078328696693342260

## Example

```
> rails g migration add_details_to_membership detail:string
> bin/super-scaffold crud-field Membership detail:text_field
```

## Details

When trying to add a crud field to Memberships, we get the following in the logs, even after ejecting the theme.

```
> rails g migration add_details_to_membership detail:string
      invoke  active_record
      create    db/migrate/20230224235059_add_details_to_membership.rb
> bin/super-scaffold crud-field Membership detail:text_field
Updating './app/views/account/memberships/_fields.html.erb'.
Couldn't find './app/views/account/memberships/show.html.erb'
Couldn't find './app/views/account/memberships/_index.html.erb'
Couldn't find './app/views/account/memberships/_membership.html.erb'
Updating './config/locales/en/memberships.en.yml'.
Updating './config/locales/en/memberships.en.yml'.
Updating './app/controllers/account/memberships_controller.rb'.
Couldn't find './app/controllers/api/v1/memberships_controller.rb'
Couldn't find './test/controllers/api/v1/memberships_controller_test.rb'
Couldn't find './test/controllers/api/v1/memberships_controller_test.rb'
Couldn't find './test/controllers/api/v1/memberships_controller_test.rb'
```

Simply moving over these files from `bullet_train-core` manually before running the scaffolder doesn't seem to do the trick.

As of now, it seems like there's no simple way to add a crud field to Memberships, but we have the following inside of `app/views/account/memberships/_fields.html.erb`, so I think developers will try to add fields themselves when they see this line:
```erb
<%# 🚅 super scaffolding will insert new fields above this line. %>
```

**Comment by gazayas** [comment]
We should be able to use #135 to scaffold new attributes to `bullet_train-core/bullet_train`, just currently missing a translation when trying to Super Scaffold with the following

```
> TARGET=local/bullet_train-core/bullet_train OTHER_TARGETS="" bin/super-scaffold crud-field Membership detail:text_field
```

**Comment by gazayas** [comment]
Actually doesn't work so bad with `Team`, it just duplicates the attribute in the form because we have `app/views/account/teams/_fields.html.erb` in the starter repository as well.

I'm thinking we should, by default, remove anything in the starter repository that hints at Super Scaffolding crud-fields for core models for the time being so we don't confuse developers who might try.

At least for `Team` (I'll have to double check) but it seems we can just delete that `fields` partial to get things working.

**Comment by gazayas** [comment]
Just confirmed in #166 that we don't need to use `TARGET` here for adding crud-fields to `Team`. `Membership` seems a little more complicated because of how it's tied to `Membership`...

**Comment by jagthedrummer** [comment]
Was just looking into this and I think we should do something similar to what we've done for the forms for these core models. For those the starter repo has a `_fields.html.erb` partial that we render inside the form form the `core` gems. I'm thinking that we could also add an `_attributes.html.erb` partial (or call it whatever) in the starter repo, render that partial in the various `show.html.erb` templates, and update the super scaffolder to inject new attributes there for the core models.

Does that sound reasonable @gazayas?

**Comment by gazayas** [comment]
@jagthedrummer Sure! My main concern is just that developers will look at the current code and assume that they can create crud-fields, leading them to get stuck on an error that's not their fault. I'm impartial (pun intended) as to how it's accomplished, so if adding a (tentatively named) `_attributes.html.erb` partial is the way to go, I'm all for it. Doesn't bother me if we place the new logic in the starter repository too (as opposed to being entirely encapsulated in the `core` gems).

**Comment by jagthedrummer** [comment]
@gazayas I think I got something figured out for this. Can you give these two PRs a look when you have a chance?

https://github.com/bullet-train-co/bullet_train/pull/1821
https://github.com/bullet-train-co/bullet_train-core/pull/990
