### ISSUE TITLE
Adding `showcase-rails` causes `uninitialized constant ApplicationHelper`.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#140]
Started seeing this after https://github.com/bullet-train-co/bullet_train-core/pull/46. Wasn't able to fix it. Also worth mentioning that I did https://github.com/bullet-train-co/bullet_train-core/pull/139 as well.

You can see this failures in CI at https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core/385/workflows/bf67c40c-a284-478d-be33-f055797a04b0/jobs/1169.

To reproduce, clone http://github.com/bullet-train-co/bullet_train and add `gem "showcase-rails"` to the `Gemfile`.

For what it's worth, I actually want this to be a fixed dependency of the `bullet_train` Ruby gem, not the starter repo. :-)

**Comment by kaspth** [comment]
> For what it's worth, I actually want this to be a fixed dependency of the `bullet_train` Ruby gem, not the starter repo. :-)

Cool, I'll make that happen. I made it optional to give us leeway to flip it later, but we can go for this now.
