### ISSUE TITLE
Add localizations in a few places

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#149]
- `_days_ago.html.erb`

https://github.com/bullet-train-co/bullet_train-core/blob/96c61361eee55ecae8cf98148d5dbc8b44b56851/bullet_train-themes/app/views/themes/base/attributes/_days_ago.html.erb#L7

- `_options.html.erb`

https://github.com/bullet-train-co/bullet_train-core/blob/96c61361eee55ecae8cf98148d5dbc8b44b56851/bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_options.html.erb#L50

- `dates_helper.rb`

https://github.com/bullet-train-co/bullet_train-core/blob/96c61361eee55ecae8cf98148d5dbc8b44b56851/bullet_train/app/helpers/account/dates_helper.rb#L8

**Comment by gazayas** [comment]
We can ignore the `dates_helper.rb` file if we're okay with #165.

**Comment by gazayas** [comment]
Linking #204

**Comment by jagthedrummer** [comment]
This seems to have been fixed somewhere along the way.
