### ISSUE TITLE
Allow users to disable password strength validations.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#15]
By default Bullet Train tries to recommend or enforce stronger passwords and passwords that haven't been compromised in a breach. However, users may not want this enabled by default, so we should create an option that allows them to disable it. For example, they should be able to do the following in `config/initializers/bullet_train.rb`

```
BulletTrain.configure do |config|
  config.strong_passwords = false
end
```

It should still be enabled by default.

**Comment by jagthedrummer** [comment]
Fixed in https://github.com/bullet-train-co/bullet_train-core/pull/23
