### ISSUE TITLE
Trix Editor HTML listings not displaying properly

### ISSUE THREAD

**Issue by kitebuggy** [bullet-train-co/bullet_train-core#150]
Bullet point and ordered lists are not displaying properly when editing them through the Trix Editor nor when displaying them in the current theme.  To reproduce, go to the online demo, create a TangibleThing and in the Trix editor, try to create a bullet point list, then save this.

When inspecting the HTML code, the ol & ul list tags are there, as are the list item tags, but they are not rendering correctly in the default/current theme.

**Comment by kitebuggy** [comment]
<img width="527" alt="1  No formatting applied" src="https://user-images.githubusercontent.com/610886/222694520-6a22989e-612a-4f2f-86bb-35acb0b84fd1.png">
<img width="475" alt="2  Bullet points (not showing)" src="https://user-images.githubusercontent.com/610886/222694524-91801bf4-5be5-48e1-a203-61c6ed419fd1.png">
<img width="459" alt="3  Numbered list (not showing)" src="https://user-images.githubusercontent.com/610886/222694528-c653d268-b5cb-4f66-b87b-d1294396f3d5.png">
<img width="534" alt="4  HTML inspection" src="https://user-images.githubusercontent.com/610886/222694535-1bfa186c-b901-4c1e-a56a-85c30821a622.png">

**Comment by gazayas** [comment]
I was able to duplicate the issue, I also noticed the text area border is red and not blue when focused, so I'll submit a PR if I make any progress.
