### ISSUE TITLE
Create Showcase examples for our theme partials.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#174]
After booting [the starter repository](http://github.com/bullet-train-co/bullet_train), you can visit `/docs/showcase` and see a UI library powered by [Showcase](https://github.com/bullet-train-co/showcase). You can see examples of how we're documenting existing partials in the `showcase/previews` directory of https://github.com/bullet-train-co/bullet_train-core/tree/main/bullet_train-themes-light/app/views alongside the actual partials in `themes/light`. 

Can we go through and create examples for all the existing light theme partials? They don't have to be perfect or event 100% complete, but just to get us started. Please ping @kaspth with any questions about how things should be documented if there are any questions.

**Comment by kaspth** [comment]
@andrewculver we merged some new showcases in #189 and #193, and it looks like #188 has the field partials.

**Comment by jagthedrummer** [comment]
Looks like this was completed in the PRs linked above.
