### ISSUE TITLE
Migrate to attributes API.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#192]
I believe we do exactly what Andy Croll is talking about [in this blog post](https://andycroll.com/ruby/assign-a-default-to-an-attribute-active-record/). Even worse, I think we generate this code into developer's applications in some cases (e.g. Action Models?)

Can we fix this across this board? :-)

**Comment by gazayas** [comment]
Cool, I'm seeing code like the following for example in `bullet_train/app/models/concerns/invitations/base.rb`. I'm assuming this is what we'll want to change, so I'll starting fishing around and see what attributes I can migrate:

```ruby
before_create :generate_uuid

...

def generate_uuid
  self.uuid = SecureRandom.hex
end
```
