### ISSUE TITLE
Checkbox field partial

### ISSUE THREAD

**Issue by dansingerman** [bullet-train-co/bullet_train-core#2]
Can we have a field partial for a vanilla checkbox that knows how to report errors?

**Comment by jagthedrummer** [comment]
I looked into this a bit today and just wanted to document what I've found so far.

It's possible to get a single checkbox rendered currently, but it _does not_ report validation errors correctly.

You can pass `single_check_box: true` to the (apparently completely undocumented) `option` (singular) field partial.

```erb
<%= render 'shared/fields/option', method: :boolean_checkbox_value, single_check_box: true %>
```

I this screenshot both attributes are validated for presence, and you can see that the single checkbox doesn't report that there's a problem with it.

![CleanShot 2024-12-16 at 16 25 08](https://github.com/user-attachments/assets/b0e13675-4622-4efd-92cc-70fa119aad9c)

Soon I'll try to dig in and figure out if we can make the `option` partial work for this or if we should add a whole new `checkbox` partial type.
