### ISSUE TITLE
Can't delete Team after creating new Membership via invite

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#231]
Context: https://discord.com/channels/836637622432170028/836637623048601633/1091054108561133648

We don't have Team deletion in place by default, so I'm curious how we want to handle this one. If we want to add a "Delete Team" button on the "Switch Teams" page, I can start working on that.

**Comment by jagthedrummer** [comment]
👍 I think a "delete team" button would be good. I've had some people ask me about this in my app.

**Comment by gazayas** [comment]
I want to tackle this one soon.

There was also a comment in Discord about preventing users from adding new teams from the dashboard: https://discord.com/channels/836637622432170028/836637623048601633/1154021736283656223

Maybe we can do the delete button and the configuration in one PR. Either way I have it on my todo list to get to this issue soon.

**Comment by jagthedrummer** [comment]
@gazayas no need to cram those things into the same PR. I think it's better if we don't.

**Comment by gazayas** [comment]
Got it!
