### ISSUE TITLE
Configuration for disabling 'Developers' menu items

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#272]
In my existing use case, the "Developers" menu item contains items that we don't yet support and which will cause confusion to end users.

A configuration disabling this functionality would be helpful.  Unfortunately, it's not as easy as ejecting the partial and commenting out the menu item as some system tests expect this functionality to be present.

**Comment by newstler** [comment]
Will introducing an ENV variable help? If it's off, partial is extracted and tests are skipped
