### ISSUE TITLE
Remove _cell.html.erb partial

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train-core#277]
Is this file still being used?

[bullet_train-themes-light/app/views/themes/light/_cell.html.erb](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-themes-light/app/views/themes/light/_cell.html.erb)

This is what it looks like rendered:

![CleanShot 2023-05-04 at 13 16 04](https://user-images.githubusercontent.com/104179/236278535-3f669667-9721-4770-8bec-be745077ca0b.gif)

**Comment by andrewculver** [comment]
Yes, it’s used by Action Models.

**Comment by pascallaliberte** [comment]
[`_box.html.erb`](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-themes-light/app/views/themes/light/_box.html.erb) could also be removed?

Here's an output of the partials included within either bullet_train or bullet_train-code repos:

<details>
<summary>Occurrences of `render "PATH"` found</summary>

<pre><code>account/billing/subscriptions/menu_item
account/billing/subscriptions/new_button
account/campaigns/index
account/campaigns/menu_item
account/integrations/stripe_installations/list
account/integrations/stripe_installations/menu_item
account/memberships/fields
account/memberships/menu_item
account/oauth/stripe_accounts/index
account/platform/access_tokens/index
account/platform/applications/breadcrumbs
account/platform/applications/menu_item
account/scaffolding/absolutely_abstract/creative_concepts/breadcrumbs
account/scaffolding/absolutely_abstract/creative_concepts/collaborators/index
account/scaffolding/absolutely_abstract/creative_concepts/creative_concept
account/scaffolding/absolutely_abstract/creative_concepts/index
account/scaffolding/absolutely_abstract/creative_concepts/menu_item
account/scaffolding/completely_concrete/tangible_things/index
account/scaffolding/completely_concrete/tangible_things/menu_item
account/scaffolding/completely_concrete/tangible_things/tangible_thing
account/shared/alert
account/shared/box
account/shared/breadcrumb
account/shared/breadcrumbs/actions
account/shared/comment
account/shared/commentary/box
account/shared/decision_line
account/shared/forms/errors
account/shared/memberships/photos
account/shared/menu
account/shared/menu/account
account/shared/menu/close
account/shared/menu/heading
account/shared/menu/item
account/shared/menu/logo
account/shared/menu/mobile
account/shared/menu/open
account/shared/menu/section
account/shared/menu/sidebar
account/shared/menu/subsection
account/shared/menu/top
account/shared/menu/user
account/shared/menu/user_items
account/shared/message
account/shared/notices
account/shared/page
account/shared/title
account/shared/workflow/box
account/teams/breadcrumbs
account/teams/fields
account/teams/menu_item
account/users/breadcrumbs
account/users/fields
account/users/form
account/users/oauth
account/webhooks/outgoing/deliveries/breadcrumbs
account/webhooks/outgoing/deliveries/index
account/webhooks/outgoing/delivery_attempts/index
account/webhooks/outgoing/endpoints/breadcrumbs
account/webhooks/outgoing/endpoints/menu_item
api/#{@version}/open_api/index
devise/shared/links
devise/shared/oauth
devise/shared/oauth/stripe
form
index
layouts/head
magic_test/support
shared/attributes/#{attribute_partial}
shared/attributes/attempt
shared/attributes/attribute
shared/attributes/base
shared/attributes/belongs_to
shared/attributes/block
shared/attributes/boolean
shared/attributes/code
shared/attributes/date
shared/attributes/date_and_time
shared/attributes/email
shared/attributes/html
shared/attributes/option
shared/attributes/options
shared/attributes/phone_number
shared/attributes/progress_bar
shared/attributes/text
shared/box
shared/bulk_action_select
shared/fields/#{type}
shared/fields/buttons
shared/fields/cloudinary_image
shared/fields/color_picker
shared/fields/date_and_time_field
shared/fields/date_field
shared/fields/email_field
shared/fields/field
shared/fields/file_field
shared/fields/options
shared/fields/password_field
shared/fields/phone_field
shared/fields/super_select
shared/fields/text_area
shared/fields/text_field
shared/fields/trix_editor
shared/layouts/head
shared/limits/error
shared/limits/form
shared/limits/index
shared/line
shared/memberships/photo
shared/superchart/chart_wrapper
shared/supercharts/chart_skeleton
shared/supercharts/chart_wrapper
shared/supercharts/filter_button
shared/supercharts/superchart
shared/tables/checkbox
shared/tables/select_all
themes/#{current_theme}/layouts/account
themes/#{current_theme}/layouts/devise
themes/#{current_theme}/layouts/mailer
themes/light/box
themes/light/layouts/head
tombstones</code></pre>
</details>

**Comment by pascallaliberte** [comment]
Found them:
* `_cell.html.erb` is used in `billing/subscriptions/_index`
* `_box.html.erb` is used in action models among others
