### ISSUE TITLE
Tailwind classes within local views/shared aren't always picked up

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train-core#28]
WIP

I've experienced this in a local repo and another person reported it in Discord. I'll document some reproducible steps after the holiday break, but I'm just putting this here in the meantime.

Symptom:

I add some classes in a file within `views/shared`, and those classes aren't picked up automatically while `bin/dev` is running. I have to stop `bin/dev`, run `bin/rails assets:precompile` before running `bin/dev` again for the classes to be read.

Maybe this is a Tailwind bug, or maybe there's a memory limit or a circular reference somehow that's causing Tailwind to bail on its class inventorying process.

**Comment by pascallaliberte** [comment]
Additionally, sometimes having a large number of complex classes in one of those files in `views/shared`, like the following, causes some of them to not even be picked up by Tailwind.

```erb
<div class="<%= "#{borders_broad? ? "border-8 border-white dark:border-darkTrim-900": "border border-lightTrim-300 dark:border-darkTrim-600" }" %> p-8 rounded-md shadow
  bg-lightBase-100 dark:bg-darkBase-750
  [--axis-color:theme('colors.lightTrim.300')] dark:[--axis-color:theme('colors.darkTrim.500')]
  [--grid-color:theme('colors.lightTrim.200')] dark:[--grid-color:theme('colors.darkTrim.800')]
  [--line-color:theme(colors.lightSplash.400/40)] dark:[--line-color:theme(colors.darkSplash.400/40)]
  [--point-color:theme('colors.lightTrim.800')] dark:[--point-color:theme('colors.darkTrim.100')]
  [--point-stroke-color:theme('colors.lightBase.100')] dark:[--point-stroke-color:theme('colors.darkBase.750')]
  [--point-stroke-color-hover:theme('colors.lightBase.150')] dark:[--point-stroke-color-hover:theme('colors.darkTrim.800')]
  [--bar-fill-color:var(--line-color)]
  [--bar-hover-fill-color:var(--point-color)]
  [--point-radius:4] md:[--point-radius:6]
  [--point-hover-radius:6] md:[--point-hover-radius:10]
  [--point-border-width:3] md:[--point-border-width:4]
  [--point-hover-border-width:2] md:[--point-hover-border-width:3]
  "
>
  <%= yield %>
</div>
```

**Comment by pascallaliberte** [comment]
This might also explain why in this project where I'm having this issue, any changes to my local files causes `bin/dev` to take a while for returning new HTTP requests following a re-building (tailwind's watch process?)

**Comment by frmsaul** [comment]
I'm having the same issue

**Comment by adampal** [comment]
@pascallaliberte did you ever get anywhere with this?
I'm currently experiencing this with a fresh clone of the starter repo.  Even just adding new classes to the main views of the application aren't picked up until I stop `bin/dev` and run `bundle exec rails assets:precompile`.

**Comment by pascallaliberte** [comment]
@adampal I just had a new clue, but haven't researched further.

Here's the clue:
I've ejected the light theme to work on my own, so I've got `application.css` locally now. Even a change to that file does not get picked up by my somehow affected setup. I need to precompile.

So it's probably not only Tailwind-related since even a change to a css file isn't picked up, although Tailwind is the postcss runner in this case. It just seems like the rebuild trigger is somehow activated, but tailwind doesn't rebuild anything.

**Comment by adampal** [comment]
The issue for me was that after running `rails assets:precompile` the first time, all the assets were compiled and placed in the `public/assets` folder.  According to the [Rails Guides](https://guides.rubyonrails.org/asset_pipeline.html#local-precompilation):
> If precompiled assets are available, they will be served — even if they no longer match the original (uncompiled) assets, even on the development server.

So once you have files in `public/assets` the live compiling assets in `app/assets/build` are not used.

The fix is to remove the precompiled assets by running:

`rails assets:clobber`
