### ISSUE TITLE
Scope Validator breaks when used with an ActiveHash

### ISSUE THREAD

**Issue by julianrubisch** [bullet-train-co/bullet_train-core#287]
When super scaffolding a `belongs_to` to an `ActiveHash` instance, a `validates :my_association, scope: true` is added to the model class.

However, this prevents saving this model, because `exists?` is not defined for an `ActiveHash::Relation` here:

https://github.com/bullet-train-co/bullet_train-core/blob/20ec101e9bb23f0858c00b2976edd6633bb8421a/bullet_train-scope_validator/lib/validators/scope_validator.rb#L8

```
/Users/jrubisch/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/active_hash-3.2.0/lib/active_hash/relation.rb:167:in `method_missing': undefined method `exists?' for #<ActiveHash::Relation
```

**Comment by jagthedrummer** [comment]
@julianrubisch I don't fully follow what you're trying to do here. Could you add some more details about how to reproduce the problem you're running into?

**Comment by julianrubisch** [comment]
Gosh that was long ago and I just opened this to make a note. 

I’ll try to reproduce it when I get back from vacation ✌️

**Comment by jagthedrummer** [comment]
@julianrubisch still curious about reproduction steps if this is something that we should fix. Maybe it's more of an edge case and there's nothing to do?

**Comment by julianrubisch** [comment]
Oh I totally forgot that. Let’s close it for now and reopen if it resurfaces.
