### ISSUE TITLE
Super select Stimulus controller methods don't work

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#290]
![Screenshot from 2023-05-10 18-49-40](https://github.com/bullet-train-co/bullet_train/assets/10546292/3216b326-32f2-4b2b-b8bc-3a2bab1da954)

https://github.com/bullet-train-co/bullet_train-core/blob/20ec101e9bb23f0858c00b2976edd6633bb8421a/bullet_train-fields/app/javascript/controllers/fields/super_select_controller.js#L97-L99

Also, `injectKeystrokeIntoTextField` below it yields a similar error when opening a super select and pressing a key.

**Comment by gazayas** [comment]
The latest release of `@bullet_train/bullet_train-fields` is v.1.0.19, and if you go to the [source code on npm.js](https://www.npmjs.com/package/@bullet-train/fields?activeTab=code) and navigate to `app/javascript/controllers/fields/super_select_controller.js`, you can see that the `focusOnTextField` and `injectKeystrokeIntoTextField` methods aren't there, so we'll need to update the package with what we currently have in `bullet_train-core` so developers can download it with yarn.

**Comment by gazayas** [comment]
@pascallaliberte Is releasing a new version something you would handle, or should we wait for Andrew?

**Comment by pascallaliberte** [comment]
> @pascallaliberte Is releasing a new version something you would handle, or should we wait for Andrew?

@gazayas Andrew is the one releasing versions right now. So it’s just that the methods are in `main` but not released?

**Comment by gazayas** [comment]
Yes, as far as I can tell.

**Comment by zackgilbert** [comment]
I'm still experiencing these errors, so I'm assuming this hasn't been fixed yet? Any ETA?

**Comment by pascallaliberte** [comment]
@zackgilbert we're picking up the pace on merging PRs and preparing releases. It should be soon. Sorry for the wait.

**Comment by gazayas** [comment]
Closing this since the new packages have been released and we're not getting the errors anymore: https://github.com/bullet-train-co/bullet_train/pull/848
