### ISSUE TITLE
Including fontawesome pro results in huge mailer payloads

### ISSUE THREAD

**Issue by julianrubisch** [bullet-train-co/bullet_train-core#293]
I noticed that both locally and in production, sending any email was timing out (I saw puma spiking at 100% and OOM errors), and set out to debug this. 

It turned out that adding font awesome pro as per https://bullettrain.co/docs/font-awesome-pro (i.e., requiring it in `application.js`) resulted in the whole FA pro CSS being included in the mails (a total payload of > 200MB!).

The default mailer template just includes the application stylesheet uncompressed and unpurged, so I think it cannot be fixed by a simple config change. I want to keep the application styles in mails, but of course this situation isn't acceptable. Do you have any thoughts on this?

_Edit_: Now that I look at it, I'm not even sure the application styles are needed in the mailers, are they?

**Comment by gazayas** [comment]
We could probably just get away with `<%= stylesheet_link_tag 'application.mailer.light', media: 'all' %>`? If we are already separating the files in the first place and writing other necessary CSS in the template, maybe it's confusing to load the regular [application](https://github.com/bullet-train-co/bullet_train-core/blob/c6c24fe852356c92e6fc7aede133de019ed211aa/bullet_train-themes-light/app/views/themes/light/layouts/_mailer.html.erb#L7) file in there too.

**Comment by gazayas** [comment]
I'm not seeing any visual differences after removing the tag, haven't checked the payload yet though.

**Comment by julianrubisch** [comment]
Yep, that was my „fix“ too. But can we be sure this won’t break stuff for other people? I don’t know how it’s used in the wild

**Comment by julianrubisch** [comment]
I am wondering, though, if including the CSS in application.js rather than CSS is the root of the issue?

It seems to bypass purging this way

**Comment by diegoauzad** [comment]
Searching in Discord for a way to reduce payload size I found this issue, are there any updates? 

Is it safe to remove the tag?, I'm new in the theme ecosystem, do I have to eject the file to edit it, right?

**Comment by jagthedrummer** [comment]
@diegoauzad, yeah, you'll have to eject the file and then edit the copy in your app.

As to it being safe, I'm not _entirely_ sure (I'm reviewing this issue for the first time), but it's at least worth trying just to see how it goes for you.

@gazayas, @julianrubisch do y'all have any more additional thoughts on this? A payload of > 200MB is certainly no good, and we should try to figure out a way to resolve that one way or another.

I'll try to look into this next week after the holiday. 🦃

**Comment by gazayas** [comment]
Thinking on a few things here.

Here's the file structure for `@fortawesome/fontawesome-free` (note that it's the free version, I don't currently have a token for fontawesome pro):

```
.
└── @fortawesome/fontawesome-free/
    └── css/
        ├── all.css
        ├── all.min.css
        ├── brands.css
        ├── brands.min.css
        ├── fontawesome.css
        ├── fontawesome.min.css
        └── etc...
```

At the very least, in the [documentation](https://bullettrain.co/docs/font-awesome-pro#4-add-font-awesome-pro-to-the-asset-pipeline) we could tell developers to use `require("@fortawesome/fontawesome-pro/css/all.min.css")` instead of `all.css`.

I wonder if we could make a separate JS file just for the fontawesome CSS and include it wherever applicable.

https://github.com/bullet-train-co/bullet_train-core/blob/3383ce9c8e461b2b682f8c321ae41db900084797/bullet_train/lib/bullet_train.rb#L152-L154

```erb
<%= stylesheet_link_tag "fontawesome" if font_awesome? %>
```

Then we could just keep it out of the mailer layout, and developers could add it in by ejecting the file if they wanted to (and we could add a note to the documentation).

Thoughts?

**Comment by Siggs2000** [comment]
Has anyone found a workaround for this without removing Fontawesome Pro from the app? I use the FA Pro icons in my app and changed the require statement to `require("@fortawesome/fontawesome-pro/css/all.min.css")` as @gazayas suggested but still end up with a payload that's way too big to pass to Postmark.

**Comment by gazayas** [comment]
Looking at the contents of `application.css`, it includes node modules with styles for some of the following libraries:
- pickr
- daterangepicker
- International Telephone Input
- select2
- Trix Editor
- Themify Icons

A lot of these are form-related and we don't need them in emails, so maybe we can remove the application tag and explicitly include themify for those who aren't using Font Awesome. Maybe wrap it with a conditional if Font Awesome is enabled.

As a side note, it looks like Themify icons in our emails aren't working to begin with.

As far as Bullet Train styles, application.mailer.light.css is a build from the original light stylesheet, so I don't think we'll be losing any core CSS styling (You can see in the package.json build that we export the original light stylesheet to `./app/assets/builds/application.mailer.light.css`, just with the light mailer config):

https://github.com/bullet-train-co/bullet_train/blob/ebc520f1bb56d990aa263b88be69ff08429283d4/package.json#L41

**Comment by Siggs2000** [comment]
Commenting out `<%= stylesheet_link_tag 'application', media: 'all'%>` from _mailer.html.erb does seem to have done the trick for now
