### ISSUE TITLE
obfuscates_id: Hashids::InputError: unable to unhash on a model with UUID id

### ISSUE THREAD

**Issue by johnphamvan** [bullet-train-co/bullet_train-core#30]
We have a model with a hierarchal dependency and a UUID as the PK. Unsure if this is relevant, but the model is also in a separate schema from the rest of the bullet_train models.

```
CREATE TABLE law.divisions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    parent_id uuid,
    # snip...
```

When we call `.update()` on the model. We get an error originating from the `obfuscates_id` gem.
```
Minitest::UnexpectedError: Hashids::InputError: unable to unhash
    app/models/division/sortable_with_siblings.rb:69:in `block (2 levels) in <module:SortableWithSiblings>'
    test/models/division/sortable_with_siblings_test.rb:42:in `block in <class:SortableWithSiblingsTest>'
```

Commenting out the `gem "bullet_train-obfuscates_id"` resolves the issue.

Sorry, I would dig into it more but https://github.com/bullet-train-co/bullet_train-core/tree/main/bullet_train-obfuscates_id/lib/bullet_train/obfuscates_id is pretty light on details. I can research if someone can give me more info on the intent of this gem and point me toward the source.

**Comment by gazayas** [comment]
Hello @johnphamvan, from this information I'm not entirely sure what the issue might be, but if I can replicate the model and the error, I can take a look at what's going on under the hood.

> I can research if someone can give me more info on the intent of this gem and point me toward the source.

[Here's the source code](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-obfuscates_id/app/models/concerns/obfuscates_id.rb). The purpose of it is so we don't have links simply like `http://localhost:3000/account/teams/1`, which is changed to `http://localhost:3000/account/teams/bJYLew`. You can see this when spinning up a new Bullet Train app and viewing the dashboard after you've registered a new user.

> Unsure if this is relevant, but the model is also in a separate schema from the rest of the bullet_train models.

Super Scaffolded models usually belong to a `Team`, so if your model is in a separate schema, this might affect your model in an unexpected way.

Can I ask how you implemented `law.divisions`? What `rails g model` commands, etc. did you use?

**Comment by jagthedrummer** [comment]
Hey @johnphamvan, can you help us out with some more details on this?

**Comment by johnphamvan** [comment]
@jagthedrummer @gazayas I still have the codebase from last year. Would it help to have access that?

**Comment by jagthedrummer** [comment]
@johnphamvan, yeah that would definitely help!

**Comment by jagthedrummer** [comment]
@johnphamvan If you can provide some more details we can look into this. If not, we can just close it for now.

**Comment by johnphamvan** [comment]
You can close it, Jeremy. I don't have the project setup to reproduce the original issue. Thanks for your help.
