### ISSUE TITLE
Nonexistent locales when accessing `?show_locales=true`

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#306]
![show locales](https://github.com/bullet-train-co/bullet_train-core/assets/10546292/2859710e-a4ff-48fd-9bb5-7a92e38c0733)

There are a few locales displayed here that don't exist:
`en.users.self.email.placeholder`
`en.users.self.email.help`
`en.users.self.password.help`

These strings are being generated in [labels_for](https://github.com/bullet-train-co/bullet_train-core/blob/350023aa4c3116f4df89c85f6dd2d7dbf8261bbf/bullet_train/app/helpers/account/forms_helper.rb#L34-L38) and [t]():

```ruby
def labels_for(form, method)
  keys = [:placeholder, :label, :help, :options_help]
  path = [model_key(form), (current_fields_namespace || :fields), method].compact
  Struct.new(*keys).new(*keys.map { |key| t((path + [key]).join("."), default: "").presence })
end
```

```ruby
# within #t
unless Rails.env.production?
  if params.present?
    if params[:log_locales] || params[:show_locales]
      # Often times we're only receiving partial keys like `.section`, so this is a crazy hack to trick I18n.t into
      # telling us what the full key ended up being.
      begin
        super(key + "💣", options.except(:default))
      rescue I18n::MissingTranslationData => exception
        full_key = exception.message.rpartition(" ").last.delete("💣")
      end
    end
  end
end
```

**Comment by gazayas** [comment]
It turns out we're okay with having keys that don't return a value, because it shows the developer that they CAN populate a value with that key (see [comment](https://github.com/bullet-train-co/bullet_train-core/pull/303#issuecomment-1660762696) in #303)

**Comment by jagthedrummer** [comment]
@gazayas With #303 merged are we good to close this issue?

**Comment by gazayas** [comment]
@jagthedrummer Yes sir! I'll go ahead and close it out.
