### ISSUE TITLE
Multitenancy check for `has_many` associations

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#318]
When creating a join model, Super Scaffolding creates a valid collections method from the following code:

https://github.com/bullet-train-co/bullet_train-core/blob/350023aa4c3116f4df89c85f6dd2d7dbf8261bbf/bullet_train-super_scaffolding/lib/scaffolding/transformer.rb#L819-L847

I've been mulling over the TODO there at the end for a bit, and can't seem to figure out what the end goal we have in mind for implementing this tenancy check looks like.

I'm assuming this could mean:
1. We check the `has_many` line for a `through:` option and ensure it's pointing to the correct model.
2. Add a check somewhere in the `valid_#{collection_name}` method to ensure we're getting the correct records.

I'd love to work on this one, just not entirely sure which direction we should take it in.

**Comment by gazayas** [comment]
I also came across the [activerecord-multi-tenant](https://github.com/citusdata/activerecord-multi-tenant) gem, so I'm not sure if we want to use this.

**Comment by jagthedrummer** [comment]
I also don't really understand what that TODO is trying to say. I get the feeling that it's something different than the problems solved by the `activerecord-multi-tenant` gem, so I don't think that gem is the answer. Maybe we just remove that TODO and close this issue?

**Comment by gazayas** [comment]
Agreed, I don't think we've run into any association-related multi-tenancy issues that I know of, and I haven't heard any problems from other devs in the Discord chat so I think it will be safe to close this one out. I'll submit a PR to remove the comment.
