### ISSUE TITLE
SuperSelectSupport: Passing in a numeric string to `create_models_if_new` will assume the model exists.

### ISSUE THREAD

**Issue by BuddyLReno** [bullet-train-co/bullet_train-core#321]
If I pass a group of ids to the `create_models_if_new` method, if one of those "ids" doesn't actually exist in the system, the method will allow that value to be returned as if it were a valid value. This seems to occur when using a super select field that has the `acceptsNew` option turned on. That field will compile selected values into an array for the backend with string IDs of the select values (ex: `["12", "55", "32"]`). If a value is created using the super select, the value becomes the text of the entry. (ex: `["12", "55", "32", "daniel"]`. As it currently works, `"daniel"` won't pass the regex check on line 15 in [super_select_support](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-fields/app/controllers/concerns/fields/super_select_support.rb) and yield to the given block.

If I use super select to add a numeric value though, that new numeric option looks exactly like an id (ex: `["12", "55", "32", "999"]`). The "999" value would pass the regex check on line 15 and return the "999" value as if the model exists. This could give a false positive and save model ids that don't exist the model. Furthermore, if I try to link to this resource using this ID, I could potentially link to an unauthorized resource if the id happened to exist somewhere in the system.

**Comment by pascallaliberte** [comment]
Here's `create_model_if_new` and `create_models_if_new`:

https://github.com/bullet-train-co/bullet_train-core/blob/0c567aabcfb3ad3e5cbad54e3a477612e3cd7673/bullet_train-fields/app/controllers/concerns/fields/super_select_support.rb#L13-L28

And an example implementation:

```rb
strong_params[:book_ids] = create_models_if_new(strong_params[:book_ids]) do |new_value|
  current_user.books.find_or_create_by(title: new_value)
end
```

* book_ids are passed back straight through if they're numerical
* if a book_id is instead a string, it'll be passed to the yielded block, which should return a new record or its id

**Comment by pascallaliberte** [comment]
We'd like a solution that:

1. Is still as compact
2. Is more clear: `if_new` is the intended shorthand, but it should really be `if_string`
3. Is documented: these methods aren't currently documented

A couple options:

* **Option 1: Create new `if_string` methods (same implementation), document best practice to validate, deprecate `if_new` methods**. In this case, we're relying on documentation for a probable security risk.
* **Option 2: Create new `filter_valid_ids_or_create_if_string(ids_or_strings, collection: nil, attribute: :id)` that both validates the ids and passes strings to the block for custom `find_or_create_by`**. In this case, we assume a default `user.books.where(id: :book_ids).pluck(:id)` is both enough and a good default. Those who want a custom validation or a custom matcher (beyond detecting numerical) can decide to extend.

**Comment by pascallaliberte** [comment]
@BuddyLReno you're invited to check out PR #591 which introduces a new `ensure_backing_models_on` method to address this issue.

**Comment by BuddyLReno** [comment]
Nice! Thanks Pascal!

**Comment by pascallaliberte** [comment]
Resolved in https://github.com/bullet-train-co/bullet_train-core/pull/591
