### ISSUE TITLE
`/account/teams/<team>/webhooks/outgoing/endpoints/new` raises undefined method `scaffolding_absolutely_abstract_creative_concepts` for #<Team when `HIDE_THINGS` is true

### ISSUE THREAD

**Issue by vfonic** [bullet-train-co/bullet_train-core#348]
I tried this on a new Bullet Train project in development and production (Heroku).

This happens in this file `app/views/account/webhooks/outgoing/endpoints/_form.html.erb`:

```erb
<%= render 'shared/fields/super_select', method: :scaffolding_absolutely_abstract_creative_concept_id,
      choices: [['None', '']] + @endpoint.creative_concepts.map { |event_type| [event_type.name, event_type.id] }, other_options: {search: true} %>
```

When calling `@endpoint.creative_concepts`, because we have in `bullet_train-outgoing_webhooks/app/models/concerns/webhooks/outgoing/endpoint_support.rb`:

```rb
  def creative_concepts
    team.scaffolding_absolutely_abstract_creative_concepts
  end
```

Which calls `scaffolding_absolutely_abstract_creative_concepts` in `scaffolding_absolutely_abstract_creative_concepts`:

```rb
    unless scaffolding_things_disabled?
      has_many :scaffolding_absolutely_abstract_creative_concepts, class_name: "Scaffolding::AbsolutelyAbstract::CreativeConcept", dependent: :destroy, enable_updates: true
    end
```

Which is disabled.

Anything that should be done here or is this sort-of expected behavior?

**Comment by vfonic** [comment]
What should be done here? The issue is that this code is in the gem, not in the Bullet Train template code, so it can't be directly fixed, only "monkey patched".

Here are the repro steps:

```sh
git clone git@github.com:bullet-train-co/bullet_train.git your_new_project_name
cd your_new_project_name
bin/configure
# optional / not relevant
# Continue setting up with GitHub? [y/n]
n
# What is the name of your new application in title case? (e.g. "Some Great Application")
Some Great Application

bin/setup
echo "HIDE_THINGS: 'true'" >> config/application.yml
bundle exec rails test
```

Without `echo "HIDE_THINGS: 'true'" >> config/application.yml` line, `bundle exec rails test` passes.

**Comment by jagthedrummer** [comment]
I just tested this in a fresh copy of the starter repo and it looks like the problem has been fixed somewhere along the way.
