### ISSUE TITLE
Docs search?

### ISSUE THREAD

**Issue by vfonic** [bullet-train-co/bullet_train-core#356]
I noticed that Bullet Train docs don't have search functionality. Algolia offers free search for open-source projects. Would you be interested in integrating Algolia search in the docs?

https://docsearch.algolia.com/
What do you think? Should we apply for this? If not, why not?

**Comment by jagthedrummer** [comment]
Thanks for the suggestion, @vfonic! This is now on the docs site:

![CleanShot 2023-08-31 at 12 08 15](https://github.com/bullet-train-co/bullet_train-core/assets/58702/5cccfe6d-3187-41f5-acb7-e61795d51cab)

**Comment by vfonic** [comment]
Fuck yeah! Thank you! 🚀 🤘
