### ISSUE TITLE
Can't nest models deeper than two levels

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#358]
Running `bin/super-scaffold crud` outputs the following help text.

```
🚅  usage: bin/super-scaffold crud <Model> <ParentModel[s]> <attribute:type> <attribute:type> ...

E.g. a Team has many Sites with some attributes:
  rails g model Site team:references name:string url:text
  bin/super-scaffold crud Site Team name:text_field url:text_area

E.g. a Section belongs to a Page, which belongs to a Site, which belongs to a Team:
  rails g model Section page:references title:text body:text
  bin/super-scaffold crud Section Page,Site,Team title:text_area body:text_area

E.g. an Image belongs to either a Page or a Site:
  Doable! See https://bit.ly/2NvO8El for a step by step guide.

E.g. Pages belong to a Site and are sortable via drag-and-drop:
  rails g model Page site:references name:string path:text
  bin/super-scaffold crud Page Site,Team name:text_field path:text_area --sortable

🏆 Protip: Commit your other changes before running Super Scaffolding so it's easy to undo if you (or we) make any mistakes.
If you do that, you can reset to your last commit state by using `git checkout .` and `git clean -d -f` .

Give it a shot! Let us know if you have any trouble with it! ✌️
```

Super Scaffolding the `Section` model doesn't work here, and running tests after Super Scaffolding it produces an error.

## Commands for Example Models
```
rails g model Site team:references name:string url:text
bin/super-scaffold crud Site Team name:text_field url:text_area
rails g model Page site:references name:string
bin/super-scaffold crud Page Site,Team name:text_field
rails g model Section page:references title:string
bin/super-scaffold crud Section Page,Site,Team title:text_field
```

## Error
```
Error:
Api::OpenApiControllerTest#test_OpenAPI_document_is_valid:
ActionView::Template::Error: Cannot modify association 'Section#team' because it goes through more than one other association.
    app/views/api/v1/open_api/index.yaml.erb:60
    test/controllers/api/open_api_controller_test.rb:6:in `block in <class:OpenApiControllerTest>'
```

## Thoughts
I'm not quite sure how to fix this one right now, but I feel like this one is pretty high-priority if we're using an example in the help output.

**Comment by gazayas** [comment]
Also not as important, but the Super Scaffolding command in the help text for `Section` won't work because the first attribute is a text area, which we now prevent from being the first attribute when creating a new model:
- https://github.com/bullet-train-co/bullet_train-core/pull/199

**Comment by gazayas** [comment]
This part in [#deep_clone](https://github.com/bullet-train-co/bullet_train-core/blob/537d1bbcbc838e398fc8271c6e1f14db31713af1/bullet_train-api/lib/bullet_train/api/example_bot.rb#L66-L81) is the culprit:

```ruby
elsif %i[belongs_to has_one].include?(reflection.macro)
  clone.send("#{name}=", instance.send(name).clone)
  # ...
end
```

Here the instance is `Section` while `name` is `team`, causing the error. Trying to work through a solution now.

**Comment by gazayas** [comment]
[Ancestry](https://github.com/stefankroes/ancestry) seems like an interesting gem to use, I don't want to implement it just for this fix though.

**Comment by gazayas** [comment]
This might have been fixed in #387, but the OpenAPI tests are currently failing so I want to wait until we figure that out to close this issue.

**Comment by jagthedrummer** [comment]
@gazayas The fix for the OpenAPI tests have been merged and I cut a new release earlier today.

(There's still the issue with an OpenAPI related test failure when running locally, but CI should be OK. https://discord.com/channels/836637622432170028/836637623048601633/1144621336866586755)

**Comment by gazayas** [comment]
@jagthedrummer The tests are passing on CI in [this PR](https://github.com/bullet-train-co/bullet_train/pull/924), so I'll go ahead and close this issue.
