### ISSUE TITLE
Some devise links are missing

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train-core#370]
@kaspth I just discovered that https://github.com/bullet-train-co/bullet_train-core/pull/368 somehow broke some of the devise forms. They're missing the "Already have an account?" and "Don't have an account?" links.

**Comment by jagthedrummer** [comment]
I suspect it was the dropping of `content_for :help` blocks.

**Comment by jagthedrummer** [comment]
Just adding back the `content_for :help` blocks didn't do the trick. I think maybe that PR just doesn't do quite what you thought it should do. I'm going to revert it for now because it's causing failures in other repos.

**Comment by jagthedrummer** [comment]
It seems like it should have failed tests in CI. Not sure why it didn't. Maybe we're not running the system tests from the starter repo in CI for `core`?

**Comment by jagthedrummer** [comment]
Here's a failed run from the `usage` repo, just for reference. I also double checked a running local instance and those links are definitely missing.

https://app.circleci.com/pipelines/github/bullet-train-pro/bullet_train-billing-usage/53/workflows/608fda00-148e-4ae3-9df1-e1f3325778a6/jobs/183

**Comment by kaspth** [comment]
@jagthedrummer thanks for finding this and sorry for breaking it, I had seen those tests fail in #159 so it seemed like it was fixed in #368.

**Comment by jagthedrummer** [comment]
No worries, it happens. I'm currently looking into why the affected tests didn't seem to run on your PR.

**Comment by jagthedrummer** [comment]
Welp, I just confirmed that the starter repo tests _do_ get run in CI for `core`. So I'm stumped as to why #368 passed CI.

https://github.com/bullet-train-co/bullet_train-core/pull/372
