### ISSUE TITLE
Required fields do not always display a red asterisk

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#379]
In the screenshot in #349, you can see that all of the fields in the form are required, but not all of them have a red asterisk indicating that they are.

The original PR implementing the style change: #107

**Comment by jagthedrummer** [comment]
I just looked into this a bit and I think this line is what causes this to be unpredictable:

https://github.com/bullet-train-co/bullet_train-core/blob/2b9dea3798d625943d12c1a959d817cac71122df/bullet_train-themes-light/app/views/themes/light/fields/_field.html.erb#L34

I think that's a good fallback, but we probably want to somehow allow the required status to be passed in.

For instance, on the user registration form the `password_confirmation` _is_ a required field, but there isn't a true validation on the `User` model for it. So it would be nice if we could pass in an option in this block that will tell the `field` partial that `password_confirmation` is required even though we don't have a validation for it.

https://github.com/bullet-train-co/bullet_train-core/blob/2b9dea3798d625943d12c1a959d817cac71122df/bullet_train/app/views/devise/registrations/new.html.erb#L16-L21

Something like:

```diff
  <%= render 'shared/fields/password_field', form: f,
    method: :password_confirmation,
+   required: true,
    other_options: {
        error: f.object.errors.full_messages_for(:password).first,
        hide_custom_error: true
    }
  %>
```

I'm not sure if it should be a top-level option, or inside the `other_options` hash. Just trying to illustrate the idea.
