### ISSUE TITLE
Can this file be removed?

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#42]
I think we don't need 
`bullet_train-outgoing_webhooks/app/views/account/webhooks/outgoing/endpoints/_endpoint.json.jbuilder` because we have `bullet_train-outgoing_webhooks/app/views/api/v1/webhooks/outgoing/endpoints/_endpoint.json.jbuilder`. Are there any other duplicates like this?

**Comment by newstler** [comment]
At least
- `bullet_train-super_scaffolding/app/views/account/scaffolding/absolutely_abstract/creative_concepts/_creative_concept.json.jbuilder` duplicates `bullet_train-super_scaffolding/app/views/api/v1/scaffolding/absolutely_abstract/creative_concepts/_creative_concept.json.jbuilder`
- `bullet_train/app/views/account/teams/_team.json.jbuilder` duplicates `app/views/api/v1/teams/_team.json.jbuilder` in the main app
