### ISSUE TITLE
TypeError: no implicit conversion of Hash into String on Scaffolded Create Controller Tests

### ISSUE THREAD

**Issue by regularlady** [bullet-train-co/bullet_train-core#44]
I'm back with something minor and non-blocking. 

### Issue

This commit: https://github.com/bullet-train-co/bullet_train-core/commit/5e6d042448abba11abe929c3c2ec11618a6301de

Is causing an issue with any scaffolded Create controller tests because it is returning a Hash and not a String. I think this was missed because the Teams controller does not have a Create test. 

### Error

TypeError: no implicit conversion of Hash into String

### Test Example 

This is a create test that was scaffolded for me. 

```
    test "create" do
      # Use the serializer to generate a payload, but strip some attributes out.
      params = {access_token: access_token}
      
      # test fails here because the return value of to_api_json has changed
      plan_data = JSON.parse(build(:plan, episode: nil).to_api_json)
      plan_data.except!("id", "episode_id", "created_at", "updated_at")
      params[:plan] = plan_data

      post "/api/v1/episodes/#{@episode.id}/plans", params: params
      assert_response :success

      # # Ensure all the required data is returned properly.
      assert_proper_object_serialization response.parsed_body

      # Also ensure we can't do that same action as another user.
      post "/api/v1/episodes/#{@episode.id}/plans",
        params: params.merge({access_token: another_access_token})
      assert_response :not_found
    end
```

Code change: 

https://github.com/bullet-train-co/bullet_train-core/blame/5e6d042448abba11abe929c3c2ec11618a6301de/bullet_train/app/models/concerns/records/base.rb#L92-L95

My app was just scaffolded this morning and tests were passing :) I was upgrading to make sure it would go smoothly. 

I wish I could point to where the Create controller tests are scaffolded from but at the moment, I'm not seeing it.

**Comment by gazayas** [comment]
I know I wasn't assigned to this, but I saw there hasn't been some activity in a while so I decided to look into it.

We changed `to_api_json` to `to_api_json.to_json`[here](https://github.com/bullet-train-co/bullet_train/pull/586) a while back, so this ensured we were getting the JSON data properly.

I submitted a PR to make the logic a little more readable, so you can check that out [here](https://github.com/bullet-train-co/bullet_train-core/pull/252) if you're interested. Besides that, I think this should be fixed for the time being.

**Comment by regularlady** [comment]
> I know I wasn't assigned to this, but I saw there hasn't been some activity in a while so I decided to look into it.
> 
> We changed `to_api_json` to `to_api_json.to_json`[here](https://github.com/bullet-train-co/bullet_train/pull/586) a while back, so this ensured we were getting the JSON data properly.
> 
> I submitted a PR to make the logic a little more readable, so you can check that out [here](https://github.com/bullet-train-co/bullet_train-core/pull/252) if you're interested. Besides that, I think this should be fixed for the time being.

@gazayas wonderful, thank you!

**Comment by jagthedrummer** [comment]
Sounds like this is fixed, so I'm going to close the issue. Please re-open it if I misunderstood.
