### ISSUE TITLE
`super_select`'s `accepts_new` option should automatically enable `search: true`.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-core#458]
See thread at https://discord.com/channels/836637622432170028/1143229058721775686/1143257596359356497 for background.

**Comment by gazayas** [comment]
@jagthedrummer Thanks for picking this one up, will try to be more diligent about these :pray:

**Comment by jagthedrummer** [comment]
No worries, @gazayas! It's a team effort.
