### ISSUE TITLE
`--link-local` flag for `bin/hack`

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train-core#463]
If I already have the `core` repo on my machine it would be nice to be able to pass a path to it to `bin/hack` so that I can use that copy, instead of checking out a fresh copy.

Something like:
```
bin/hack --link-local ../bullet_train-core
```

**Comment by gazayas** [comment]
We have `bin/hack --link` which automatically links up to `./local/bullet_train-core`, should I update it to take a custom path like `bin/hack --link ../bullet_train-core`?
