### ISSUE TITLE
ExampleBot doesn't reset tables when an error occurs

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#482]
https://github.com/bullet-train-co/bullet_train-core/blob/1a9cce94b2893f464c4d9d2317152a4d1598fa57/bullet_train-api/lib/bullet_train/api/example_bot.rb#L7-L40

These functions reset the table FKs, but if an error occurs at any point they do not get reset because the exception doesn't get handled.

**Comment by jagthedrummer** [comment]
Good find, @olbrich!
