### ISSUE TITLE
Intended way to call account_load_and_authorize?

### ISSUE THREAD

**Issue by aaricpittman** [bullet-train-co/bullet_train-core#586]
What is the intended way to call the [account_load_and_authorize](https://github.com/bullet-train-co/bullet_train-core/blob/0af4a51e7254b2412ee26509de0ee1d9ab0a9f43/bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb#L31) method?

I assumed it was like this

```ruby
account_load_and_authorize_resource :thing, through: :team, through_association: :scaffolding_things
```

However, [this comment](https://github.com/bullet-train-co/bullet_train-core/blob/0af4a51e7254b2412ee26509de0ee1d9ab0a9f43/bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb#L44-L46) seems to indicate otherwise.

**Comment by jagthedrummer** [comment]
Can't say that I know for sure. Based on what I see in the codebase we do a lot of the pattern that you assumed. And unfortunately we don't seem to have much history in git about this package.

@andrewculver, can you shed any light here?

**Comment by jagthedrummer** [comment]
@aaricpittman, are you getting errors when you try to use it that way?

**Comment by aaricpittman** [comment]
No, was wanting to clean up and add some tests to that method next.

Also, just noticed [this comment](https://github.com/bullet-train-co/bullet_train-core/blob/0af4a51e7254b2412ee26509de0ee1d9ab0a9f43/bullet_train-super_load_and_authorize_resource/app/controllers/concerns/bullet_train/loads_and_authorizes_resource.rb#L32) a little earlier seems to indicate what I assumed is correct.

**Comment by kaspth** [comment]
Yeah, it seems like we're using both styles throughout Bullet Train, so in my refactor in #525 I opted to just support both https://github.com/bullet-train-co/bullet_train-core/pull/525/commits/fd5472d551e1248a20bcd20bccec5537a69001ba

**Comment by andrewculver** [comment]
The correct usage is [what Super Scaffolding produces by default](https://github.com/bullet-train-co/bullet_train-core/blob/main/bullet_train-super_scaffolding/app/controllers/account/scaffolding/completely_concrete/tangible_things_controller.rb#L2).
