### ISSUE TITLE
Raise error when Super Scaffolding if `rails g model` was previously executed

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#603]
Now that #547 has been merged, we don't need to run `rails g model ...`. However, if someone DOES run it, we don't raise an error, and the Scaffolder continues to add/edit files:

```
> bin/super-scaffold crud Project Team title:text_field --navbar="ti.ti-world"
Generating Project model with 'bin/rails generate model Project team:references title:string'

The name 'Project' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative or use --skip-collision-check or --force to skip this check and run this generator again.
Writing './app/controllers/account/projects_controller.rb'.
Fixing Standard Ruby on './app/controllers/account/projects_controller.rb'.
Writing './app/views/account/projects/_index.html.erb'.
Writing './app/views/account/projects/_form.html.erb'.
Writing './app/views/account/projects/_menu_item.html.erb'.
...
```

In trying to find a solution for this, I kept track of the thread and waited for it to stop:
```ruby
begin
  generator_thread = Thread.new do
    `#{generation_command}` unless @options["skip-migration-generation"]
  end
  generator_thread.join # Wait for the thread to finish.
rescue => e
  # Handle error...
end
```

However, this doesn't actually rescue the error, and I can't quite seem to grab the error message which says the model already exists.

The original Rails error message can be found [here](https://github.com/rails/rails/blob/2d271a4b901e7a7dae8ba4e5e83edfebdee278e8/railties/lib/rails/generators/base.rb#L279-L281). Although I would like to call `class_collisions`, it's in a private method.

Would we be okay with just scanning our instances of ActiveRecord and seeing if the model exists already?

**Comment by kaspth** [comment]
Ah ok, so it looks like the subprocess that's spawned hangs waiting on user input, e.g. `n` to abort.

Maybe we could do something with `Process.spawn` then grab the `pid` and kill it after 5 seconds? The tough part is if the true command takes more than 5 minutes.

Ruby's `IO` class has some utilities for dealing with this kind of thing: https://rubyapi.org/3.2/o/io#method-c-popen
I've never used it, but it may be possible to use `gets`, `read` to detect the collision and then `puts` a response on the pipe.

Or maybe we can use `trap` or `rescue Interrupt`? Like this:

```ruby
trap "SIGINT" do # Catches ctrl-c like `bin/rails server`
  puts "We'll be generating the model now, if it's already there it'll stall, hit ctrl-c to skip the model generation."
  `` # Command
end
```

```ruby
begin
  puts "We'll be generating the model now, if it's already there it'll stall, hit ctrl-c to skip the model generation."
  `` # Command
rescue Interrupt
end
```
