### ISSUE TITLE
Implement a home page

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#615]
We haven't had a homepage for Bullet Train for a while, but I think it would be good to have one with a navbar that links to the login page and the documentation.

Right now, you can access the Public home page by commenting out the following and adding `def index ... end`:

https://github.com/bullet-train-co/bullet_train/blob/4723c0091de1a64c5a1eaf10f821fb7ccf065341/app/controllers/public/home_controller.rb#L3-L4

Maybe on this page we could write something like "Welcome to Bullet Train!" and have a big Bullet Train insignia in the center, similar to what a new Rails app looks like:

<img width="1435" alt="スクリーンショット 2023-10-14 21 28 05" src="https://github.com/bullet-train-co/bullet_train-core/assets/10546292/dc011a34-56f2-4b43-8394-a7a2440f698f">

**Comment by jagthedrummer** [comment]
I think that's a great idea! And would make for one less thing that downstream devs have to figure out as a first step.

**Comment by gazayas** [comment]
As a side note, I think this would be a follow-up PR, but I want to use our navbar in the public interface as well.

**Comment by gazayas** [comment]
Currently working on this one. Hoping to implement the following:
1. A fade background like what we have with the [pricing layout](https://github.com/bullet-train-co/bullet_train-core/blob/eb3f1b8bf6787e87cc7dbd273ccfcc99c32b32d4/bullet_train-themes-light/app/views/themes/light/layouts/_pricing.html.erb#L8-L10)
2. Fade in the Bullet Train logo
3. Fade in "Bullet Train" under the logo shortly after
4. Link to the docs and sign in page.

**Comment by gazayas** [comment]
Changed the issue to just "Implement a home page"

If we want a public navbar, it should probably be placed in another PR.
