### ISSUE TITLE
Address field label and content don't match

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#634]
I was working with address fields today and noticed this. If you set `Country` to `United States`, the dependent frame shows `State`.

![image](https://github.com/bullet-train-co/bullet_train-core/assets/10546292/eeb88674-f62e-4487-a73b-51113eb098cc)

However, the drop down shows territories as well.

![image](https://github.com/bullet-train-co/bullet_train-core/assets/10546292/c83e73fd-360c-41dc-b986-8ec79a6d8db3)

Should we change the label, or the drop down's contents?

cc/ @pascallaliberte

**Comment by pascallaliberte** [comment]
Good catch. "State or Territory" it should be. There's [this mention in the docs](https://github.com/bullet-train-co/bullet_train-core/blob/d487d89d1cbe6abef4a102e8e911b0e6d5c4eb72/bullet_train/docs/field-partials/dynamic-forms-dependent-fields.md?plain=1#L75) to update also.
