### ISSUE TITLE
Consider using `link_to_unless_current` for conditional links in breadcrumbs

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#652]
https://github.com/bullet-train-co/bullet_train-core/blob/cdccbdd270c62592458447e9ee0af5550fdb781c/bullet_train-themes-light/app/views/themes/light/_breadcrumb.html.erb#L17-L21

Could become...

```erb
    <%= link_to_unless_current(label, url, class: "#{item_style} hover:text-slate-700 hover:underline dark:text-primary-300") do %>
       <span class="<%= item_style %>"><%= label %></span> 
    <% end %> 
```

This is purely a style thing.

**Comment by jagthedrummer** [comment]
I think we should probably leave this alone unless it's causing problems. As it stands now you get either an `a` tag with text inside it OR a `span` tag with text inside it, but the proposed change would result in sometimes getting `span => text` and sometimes getting `a => span => text`. That might cause problems if people have written custom CSS to target the breadcrumbs.

Happy to revisit this if there's a reason to do so.
