### ISSUE TITLE
`_date_and_time.html.erb` attribute should adjust for user / team's timezone

### ISSUE THREAD

**Issue by olbrich** [bullet-train-co/bullet_train-core#661]
https://github.com/bullet-train-co/bullet_train-core/blob/764ed50fb24fa1c4e7e6ee7c75aa0ba4f3ccf76d/bullet_train-themes/app/views/themes/base/attributes/_date_and_time.html.erb#L8

The call to `object.public_send(attribute)` should probably be `object.public_send(attributes)&.in_time_zone(current_user.time_zone || current_team.time_zone || "UTC")`.

This is similar to what is done in https://github.com/bullet-train-co/bullet_train-core/blob/764ed50fb24fa1c4e7e6ee7c75aa0ba4f3ccf76d/bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_date_and_time_field.html.erb#L53

**Comment by jagthedrummer** [comment]
I just tested this and as far as I can tell we're already adjusting the time based on the users time zone. It happens in `display_date_and_time` when it calls `local_time` on the incoming `timestamp`.

https://github.com/bullet-train-co/bullet_train-core/blob/fcbb448eec0c637d72931c900020a48989163909/bullet_train-fields/app/helpers/account/dates_helper.rb#L32-L56

If there are scenarios where this isn't happening correctly it would be helpful to have some reproduction steps so we can investigate. For now I'm going to close this, feel free to reopen it with more details if there's a specific scenario that's causing problems.
