### ISSUE TITLE
Route namespace resolution bug?

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train-core#690]
@gazayas I just rebased [the branch for running individual gem tests in GitHub CI](https://github.com/bullet-train-co/bullet_train-core/pull/569) and I started seeing a new failure there.

```
Failure:
Scaffolding::RoutesFileManipulatorTest#test_find_namespaces_at_the_root_level_returns_{"webhooks"=>46,_"incoming"=>47}_for_`webhooks`_under_`incoming` [/home/runner/work/bullet_train-core/bullet_train-core/bullet_train-super_scaffolding/test/lib/scaffolding/routes_file_manipulator_test.rb:50]:
--- expected
+++ actual
@@ -1 +1 @@
-{"webhooks"=>46, "incoming"=>47}
+{"webhooks"=>154, "incoming"=>47}


rails test test/lib/scaffolding/routes_file_manipulator_test.rb:48
```

It looks like it's related to https://github.com/bullet-train-co/bullet_train-core/pull/678

The test is failing in the same way locally for me on my branch, but if I revert that PR in my branch it starts passing again.

Unfortunately `bullet_train-super_scaffolding` is currently excluded from running the individual gem test in Circle, so that's how it snuck past us. Maybe it's a weird edge case since it's only triggering a failure in the gem tests, and not in any of the starter repo tests.

**Comment by gazayas** [comment]
@jagthedrummer Oof, alright I'll look into this

**Comment by gazayas** [comment]
I'm going to need some more time with this one, the issue is a little more complicated than I expected. Definitely has to do with the shifting of the array that I mentioned in #678, I'm going to have to find a way to handle this in a way that makes the most sense and is easy to read. I'm okay with reverting this in the meantime. Will submit a PR once I get things to work.

**Comment by jagthedrummer** [comment]
OK, I'm gonna go ahead and revert #678 for now. And will get #569 merged so we have coverage for this.
