### ISSUE TITLE
bin/hack: make sure bullet_train-themes-tailwind_css is loaded from local/bullet_train-core

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train-core#80]
When running `bin/hack`, the version of `bullet_train-themes-tailwind_css` being searched for shared views is still the one bundled within `bullet_train-themes-light`, and so updates to that gem from `local/bullet_train-core/bullet_train-themes-tailwind_css` aren't being picked up.

Maybe make `bin/hack` add a line to the Gemfile upon running, right after `gem "bullet_train-themes-light"`
```
gem "bullet_train-themes-tailwind_css", path: "local/bullet_train-core/bullet_train-themes-tailwind_css"
```

**Comment by pascallaliberte** [comment]
Also, the `bullet_train-field` gem isn't being referenced:
```
gem "bullet_train-fields", path: "local/bullet_train-core/bullet_train-fields"
```

**Comment by gazayas** [comment]
Good catches here, I wonder how we should handle these. I'm sure there's a reason `bullet_train-themes-tailwind-css` and `bullet_train-fields` aren't already in the Gemfile in the original starter repository, but at the same time it would be confusing to not see changes reflected in development after running `bin/hack` and editing files in those packages.

`bin/hack --watch-js bullet_train-fields` definitely works for the JavaScript there, but if changes in the views aren't being reflected then maybe we can add the two packages when linking and then just remove the lines when running `bin/hack --reset`.

**Comment by pascallaliberte** [comment]
> we can add the two packages when linking and then just remove the lines when running `bin/hack --reset`.

That's what I was thinking we could do.
