### ISSUE TITLE
Action Models select multiple no longer working

### ISSUE THREAD

**Issue by pascallaliberte** [bullet-train-co/bullet_train-core#807]
Since the following commit, the Select Multiple mode used in Action Models no longer shows the other bulk actions.

https://github.com/bullet-train-co/bullet_train-core/commit/6edf1875f334553c9088c96e2d1d8b257f777ad0

![CleanShot 2024-03-31 at 16 15 05](https://github.com/bullet-train-co/bullet_train-core/assets/104179/75522856-3890-4c04-85c6-56a24d26231f)

It's probably due to the removal of `option_field_options[:data]` which I `bulk_actions` are using here:

https://github.com/bullet-train-pro/bullet_train-action_models/blob/49797fd4b680458c3612b07d3c0ec987a2b74d87/app/views/shared/tables/_checkbox.html.erb#L7

**Comment by gazayas** [comment]
Just noticed this came up on Discord, thanks for opening this issue @pascallaliberte :pray:
