### ISSUE TITLE
The buttons field partial doesn't handle options correctly

### ISSUE THREAD

**Issue by tangopium** [bullet-train-co/bullet_train-core#815]
I noticed, that (at least) in the last version 1.7.2. the buttons field partial doesn't handle the options correctly.
If an array of `options` is passed as described [here](https://bullettrain.co/docs/field-partials/buttons), I get the error the error `undefined method each for nil` at [this](https://github.com/bullet-train-co/bullet_train-core/blob/97d4f10dbd3293052afc9cce36c0cc97f24f095a/bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_buttons.html.erb#L48) point. If I pass the parameter `button_field_options` instead (as suggested [here)](https://github.com/bullet-train-co/bullet_train-core/blob/97d4f10dbd3293052afc9cce36c0cc97f24f095a/bullet_train-themes-tailwind_css/app/views/themes/tailwind_css/fields/_buttons.html.erb#L10), I only get one empty button. Just if I pass the additional parameter `button_field_buttons` with an non-empty array (the content doesn't matter and is not used), the buttons are show correctly.

**Comment by jagthedrummer** [comment]
Thanks, @tangopium. This was relatively recently deprecated and it looks like we didn't get the deprecation message quite right. I'm going to get that fixed now and update the docs to match the new reality.
