### ISSUE TITLE
Formatting for shared/attributes/number

### ISSUE THREAD

**Issue by swombat** [bullet-train-co/bullet_train-core#817]
Also discussed at https://discord.com/channels/836637622432170028/1230104701861756999

The current implementation of the `shared/attribute/number` partial is very limited as it doesn't allow any Rails number formatting, resorting instead to `sprintf` formatting, which is very basic (for example, can't do thousands-delimiters).

Here's an updated `_number.html.erb` that could be included in the next version of bullettrain:

```
<% # Ejected from `bullet_train-themes-1.7.2/app/views/themes/base/attributes/_number.html.erb`. %>

<% object ||= current_attributes_object %>
<% strategy ||= current_attributes_strategy || :none %>
<% url ||= nil %>
<% format ||= nil %>
<% format_helper ||= nil %>
<% format_helper_args ||= {} %>
<% options ||= {} %>

<% if object.public_send(attribute).present? %>
  <%= render 'shared/attributes/attribute', object: object, attribute: attribute, strategy: strategy do %>
    <% if format %>
      <%= sprintf(format, object.public_send(attribute)) %>
    <% elsif format_helper %>
      <%= ActiveSupport::NumberHelper.send(format_helper, object.public_send(attribute), **format_helper_args) %>
    <% else %>
      <%= object.public_send(attribute) %>
    <% end %>
  <% end %>
<% end %>
```

This then supports both passing the name of the rails helper _and_ giving it additional parameters, as follows:

```
  <%= render 'shared/attributes/number', attribute: :input_tokens, format_helper: "number_to_delimited", format_helper_args: { delimiter: '/' } %>
```

Hope this helps!

**Comment by jagthedrummer** [comment]
This was fixed in https://github.com/bullet-train-co/bullet_train-core/pull/818. Thanks, @swombat!

**Comment by swombat** [comment]
Yay! You're welcome!
