### ISSUE TITLE
CircleCI consistently raising undefined local variable or method error

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-core#99]
We are consistently getting the following error in CircleCI for the starter repository minitest tests, although all tests are passing locally:

```
NameError: undefined local variable or method `rendering_options' for #<TurboDeviseController::Responder:0x00007f8ec49daaf8 ...
```

If you look [the pipeline](https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-core?branch=remove-comment-about-platform) for #92 for example, you can see that the test was initially passing (I only deleted a comment, so the code itself shouldn't be affected). However, I thought something was up so I re-ran the tests, and lo and behold the test failed with the same error.

**Comment by adampal** [comment]
+1 on this. I just pushed a branch and hit the same error with code changes that should be unrelated.

Could it be a dependency on the CI image got updated and broke something?
